// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqwgbfzznwnotyplunaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxd2diZnp6bndub3R5cGx1bmF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5NTY3OTUsImV4cCI6MjA1NjUzMjc5NX0.IIXTDPCln_f35UbDzDFH9s6uo3DCjD1mJrBxv3PCZGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);